// Test fixture for the additive-minor-bump versioning property test
// (spec R5 S5.3). MiniServerInfo mirrors an OLD client schema that only
// knows field 1 of ServerInfo. Fields 2 and 3 of ServerInfo must
// survive a round-trip through this old schema as unknown fields.
//
// This fixture is test-only: it is NOT part of the wire contract and is
// never sent or received by the server.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: mini.proto

package testfixture

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MiniServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtoVer      int32                  `protobuf:"varint,1,opt,name=protoVer,proto3" json:"protoVer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniServerInfo) Reset() {
	*x = MiniServerInfo{}
	mi := &file_mini_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniServerInfo) ProtoMessage() {}

func (x *MiniServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mini_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniServerInfo.ProtoReflect.Descriptor instead.
func (*MiniServerInfo) Descriptor() ([]byte, []int) {
	return file_mini_proto_rawDescGZIP(), []int{0}
}

func (x *MiniServerInfo) GetProtoVer() int32 {
	if x != nil {
		return x.ProtoVer
	}
	return 0
}

var File_mini_proto protoreflect.FileDescriptor

const file_mini_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mini.proto\x12\x12mmo.v1.testfixture\",\n" +
	"\x0eMiniServerInfo\x12\x1a\n" +
	"\bprotoVer\x18\x01 \x01(\x05R\bprotoVerBdZMgithub.com/luisplata/mmo-api-server/internal/protocol/testfixture;testfixture\xaa\x02\x12Mmo.V1.TestFixtureb\x06proto3"

var (
	file_mini_proto_rawDescOnce sync.Once
	file_mini_proto_rawDescData []byte
)

func file_mini_proto_rawDescGZIP() []byte {
	file_mini_proto_rawDescOnce.Do(func() {
		file_mini_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mini_proto_rawDesc), len(file_mini_proto_rawDesc)))
	})
	return file_mini_proto_rawDescData
}

var file_mini_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mini_proto_goTypes = []any{
	(*MiniServerInfo)(nil), // 0: mmo.v1.testfixture.MiniServerInfo
}
var file_mini_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mini_proto_init() }
func file_mini_proto_init() {
	if File_mini_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mini_proto_rawDesc), len(file_mini_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mini_proto_goTypes,
		DependencyIndexes: file_mini_proto_depIdxs,
		MessageInfos:      file_mini_proto_msgTypes,
	}.Build()
	File_mini_proto = out.File
	file_mini_proto_goTypes = nil
	file_mini_proto_depIdxs = nil
}
